include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use_from_same_package: info

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - prefer_final_locals
    - prefer_interpolation_to_compose_strings
    - unawaited_futures
    - unnecessary_await_in_return
    - use_super_parameters
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
