name: fluxy
packages:
  - .
  - packages/*
  - example

scripts:
  analyze:
    exec: flutter analyze .
    description: Run `flutter analyze` in all packages.
  get:
    exec: flutter pub get
    description: Run `flutter pub get` in all packages.
  clean:
    exec: flutter clean
    description: Run `flutter clean` in all packages.
