name: fluxy
description: "Core engine of the Fluxy framework including UI, state management, HTTP, and motion."
version: 1.0.1
homepage: https://github.com/swaingithub/fluxy
repository: https://github.com/swaingithub/fluxy

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0
  args: ^2.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

executables:
  fluxy: fluxy
