/// THIS FILE IS AUTO-GENERATED BY THE FLUXY CLI.
/// DO NOT EDIT MANUALLY.

import 'package:flutter/foundation.dart';
import 'package:fluxy/fluxy.dart';
import 'package:fluxy_haptics/fluxy_haptics.dart';
import 'package:fluxy_device/fluxy_device.dart';
import 'package:fluxy_logger/fluxy_logger.dart';
import 'package:fluxy_camera/fluxy_camera.dart';
import 'package:fluxy_auth/fluxy_auth.dart';
import 'package:fluxy_notifications/fluxy_notifications.dart';
import 'package:fluxy_storage/fluxy_storage.dart';
import 'package:fluxy_biometric/fluxy_biometric.dart';
import 'package:fluxy_connectivity/fluxy_connectivity.dart';
import 'package:fluxy_permissions/fluxy_permissions.dart';
import 'package:fluxy_websocket/fluxy_websocket.dart';
import 'package:fluxy_sync/fluxy_sync.dart';
import 'package:fluxy_presence/fluxy_presence.dart';
import 'package:fluxy_geo/fluxy_geo.dart';


void registerFluxyPlugins() {
  try {
    Fluxy.register(FluxyHapticsPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyHapticsPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyHapticsPlugin: $e");
  }
  try {
    Fluxy.register(FluxyDevicePlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyDevicePlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyDevicePlugin: $e");
  }
  try {
    Fluxy.register(FluxyLoggerPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyLoggerPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyLoggerPlugin: $e");
  }
  try {
    Fluxy.register(FluxyCameraPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyCameraPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyCameraPlugin: $e");
  }
  try {
    Fluxy.register(FluxyAuthPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyAuthPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyAuthPlugin: $e");
  }
  try {
    Fluxy.register(FluxyNotificationsPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyNotificationsPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyNotificationsPlugin: $e");
  }
  try {
    Fluxy.register(FluxyStoragePlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyStoragePlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyStoragePlugin: $e");
  }
  try {
    Fluxy.register(FluxyBiometricPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyBiometricPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyBiometricPlugin: $e");
  }
  try {
    Fluxy.register(FluxyConnectivityPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyConnectivityPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyConnectivityPlugin: $e");
  }
  try {
    Fluxy.register(FluxyPermissionsPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyPermissionsPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyPermissionsPlugin: $e");
  }
  try {
    Fluxy.register(FluxyWebSocketPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyWebSocketPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyWebSocketPlugin: $e");
  }
  try {
    Fluxy.register(FluxySyncPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxySyncPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxySyncPlugin: $e");
  }
  try {
    Fluxy.register(FluxyPresencePlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyPresencePlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyPresencePlugin: $e");
  }
  try {
    Fluxy.register(FluxyGeoPlugin());
    debugPrint("[INIT] [Platform] Auto-registered: FluxyGeoPlugin");
  } catch (e) {
    debugPrint("[INIT] [Platform] Failed to auto-register FluxyGeoPlugin: $e");
  }
}

