name: fluxy_permissions
description: Permission management plugin for the Fluxy framework.
version: 1.1.0
homepage: https://github.com/swaingithub/fluxy
repository: https://github.com/swaingithub/fluxy
issue_tracker: https://github.com/swaingithub/fluxy/issues
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  fluxy: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true




