name: fluxy_stream_bridge
description: Reactive bridge for connecting Dart Streams to Fluxy signals.
version: 1.2.0
homepage: https://github.com/swaingithub/fluxy
repository: https://github.com/swaingithub/fluxy
issue_tracker: https://github.com/swaingithub/fluxy/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  fluxy: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true




