import '../../fluxy.dart';

/// THIS FILE IS AUTO-GENERATED BY THE FLUXY CLI.
/// DO NOT EDIT MANUALLY.
/// 
/// This registry auto-registers plugins installed via 'fluxy plugin add'.

void registerFluxyPlugins() {
  // Example of what the generator would produce:
  Fluxy.register(FluxyStoragePlugin());
  Fluxy.register(FluxyAnalyticsPlugin());
  Fluxy.register(FluxyPermissionsPlugin());
  Fluxy.register(FluxyAuthPlugin());
  Fluxy.register(FluxyCameraPlugin());
  Fluxy.register(FluxyNotificationsPlugin());
  Fluxy.register(FluxyConnectivityPlugin());
  Fluxy.register(FluxyBiometricPlugin());
}
