// --- MOCK DATA ---
final categories = ['All', 'Beaches', 'Mountains', 'Cities', 'Nature'];

final destinations = [
  {
    'id': 1,
    'title': 'Bali Bliss',
    'location': 'Indonesia',
    'image': 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    'price': '\$850',
    'rating': 4.9,
    'category': 'Beaches',
    'description': 'Experience the tropical paradise of Bali with its stunning beaches, vibrant culture, and lush landscapes. Perfect for those seeking both relaxation and adventure.',
  },
  {
    'id': 2,
    'title': 'Santorini Sunset',
    'location': 'Greece',
    'image': 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    'price': '\$1,200',
    'rating': 4.8,
    'category': 'Cities',
    'description': 'The iconic white-washed buildings and blue domes overlooking the Aegean Sea. Santorini offers the most spectacular sunsets in the world.',
  },
  {
    'id': 3,
    'title': 'Swiss Alps Escape',
    'location': 'Switzerland',
    'image': 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80',
    'price': '\$1,500',
    'rating': 4.9,
    'category': 'Mountains',
    'description': 'Breath-taking mountain peaks and crystal clear lakes in the heart of Europe. A heaven for skiers in winter and hikers in summer.',
  },
  {
    'id': 4,
    'title': 'Kyoto Zen',
    'location': 'Japan',
    'image': 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    'price': '\$950',
    'rating': 4.7,
    'category': 'Cities',
    'description': 'Discover ancient temples, traditional tea houses, and beautiful cherry blossoms. Kyoto is the cultural heart of Japan.',
  },
  {
    'id': 5,
    'title': 'Maldives Magic',
    'location': 'Maldives',
    'image': 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    'price': '\$2,100',
    'rating': 5.0,
    'category': 'Beaches',
    'description': 'Luxury overwater villas and pristine turquoise waters for the ultimate relaxation. The Maldives defines the premium tropical experience.',
  },
];
