name: fluxy_platform
description: "A meta-package for the Fluxy framework that includes the core engine and all official plugins."
version: 1.1.0
homepage: https://github.com/swaingithub/fluxy
repository: https://github.com/swaingithub/fluxy
issue_tracker: https://github.com/swaingithub/fluxy/issues

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  fluxy: ^1.2.0
  fluxy_camera: ^1.1.0
  fluxy_notifications: ^1.1.0
  fluxy_connectivity: ^1.1.0
  fluxy_permissions: ^1.1.0
  fluxy_storage: ^1.1.0
  fluxy_auth: ^1.1.0
  fluxy_analytics: ^1.1.0
  fluxy_biometric: ^1.1.0
  fluxy_ota: ^1.1.0
  fluxy_haptics: ^1.1.0
  fluxy_logger: ^1.1.0
  fluxy_device: ^1.1.0
  fluxy_sync: ^1.1.0
  fluxy_websocket: ^1.1.0
  fluxy_geo: ^1.1.0
  fluxy_presence: ^1.1.0
  fluxy_stream_bridge: ^1.1.0

flutter:
  uses-material-design: true

