/// THIS FILE IS AUTO-GENERATED BY THE FLUXY CLI.
/// DO NOT EDIT MANUALLY.

import 'package:flutter/foundation.dart';
import 'package:fluxy/fluxy.dart';


void registerFluxyPlugins() {
  // No modular plugins detected in pubspec.yaml
}

