/// THIS FILE IS AUTO-GENERATED BY THE FLUXY CLI.
/// DO NOT EDIT MANUALLY.
library fluxy_registry;

// No imports needed


void registerFluxyPlugins() {
  // No modular plugins detected in pubspec.yaml
}

